#!/bin/csh

cp drv_in_test2 drv_in
cp atm_in_test2 atm_in
cp lnd_in_test2 lnd_in

#mv ccsm.exe ccsm0.exe

#nohup mpirun -nolocal -np 128 -host n14,n15,n16,n17 ./ccsm.exe >& runlog &
#nohup mpirun -nolocal -np 128 -host n13,n14,n15,n16 ./ccsm0.exe >& runlog0 &
#nohup mpirun -nolocal -np 128 -host n9,n10,n11,n12 ./ccsm0.exe >& runlog0 &
nohup mpirun -nolocal -np 128 -host n0,n1,n2,n3 ./ccsm.exe >& runlog &
#nohup mpirun -nolocal -np 128 -host n0,n10,n11,n12 ./ccsm.exe >& runlog &
#nohup mpirun -nolocal -np 128 -host n14,n15,n16,n17 ./ccsm.exe >& runlog &
#nohup mpirun -nolocal -np 128 -host n5,n6,n7,n8 ./ccsm.exe >& runlog &
#nohup mpirun -nolocal -np 128 -host n0,n14,n15,n16 ./castest3.exe >& runlog3 &

