#!/bin/csh

cp drv_in_test2 drv_in
cp atm_in_test2 atm_in
cp lnd_in_test2 lnd_in

nohup mpirun -nolocal -np 128 -host n0,n1,n2,n4 ./ccsm.exe >& runlog &
#nohup mpirun -nolocal -np 128 -host n0,n10,n11,n12 ./ccsm.exe >& runlog &
#nohup mpirun -nolocal -np 128 -host n10,n11,n12,n13 ./ccsm.exe >& runlog &
#nohup mpirun -nolocal -np 128 -host n14,n15,n16,n17 ./ccsm.exe >& runlog &
#nohup mpirun -nolocal -np 128 -host n6,n7,n8,n9 ./ccsm.exe >& runlog &
#nohup mpirun -nolocal -np 128 -host n0,n14,n15,n16 ./castest3.exe >& runlog3 &

