#!/bin/csh

cp drv_in_test3b drv_in
cp atm_in_test3b atm_in
cp lnd_in_test2 lnd_in
mv ccsm.exe ccsm51.exe

nohup mpirun -nolocal -np 128 -host n13,n14,n15,n16 ./ccsm51.exe >& runlog51 &
#nohup mpirun -nolocal -np 128 -host n9,n10,n11,n12 ./ccsm51.exe >& runlog51 &
#nohup mpirun -nolocal -np 128 -host n0,n1,n2,n4 ./ccsm45.exe >& runlog45 &
#nohup mpirun -nolocal -np 128 -host n14,n15,n16,n17 ./ccsm.exe >& runlog3 &
#nohup mpirun -nolocal -np 128 -host n0,n10,n11,n12 ./ccsm.exe >& runlog &
#nohup mpirun -nolocal -np 128 -host n10,n11,n12,n13 ./castest2.exe >& runlog2 &
#nohup mpirun -nolocal -np 128 -host n5,n6,n7,n8 ./ccsm47.exe >& runlog47 &
#nohup mpirun -nolocal -np 128 -host n13,n14,n15,n16 ./ccsm5.exe >& runlog5 &

